name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
      shell: bash

    - name: Run Test
      run: |
        coverage run -m pytest
      shell: bash

    - name: Check Coverage
      run: |
        coverage report -m
      shell: bash

  scan:
    name: Static Code Analysis
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
        shell: bash

      - name: Code Scan
        uses: jpetrucciani/prospector-check@master

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build the first api docker image
      run: docker build -t mrnothing01/kube-docker-fastapi:latest ./api
      shell: bash
    
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: mrnothing01/kube-docker-fastapi

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    