name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
      shell: bash

    - name: Run Test
      run: |
        coverage run -m pytest
      shell: bash

    - name: Check Coverage
      run: |
        coverage report -m
      shell: bash

  scan:
    name: Static Code Analysis
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
        shell: bash

      - name: Code Scan
        uses: jpetrucciani/prospector-check@master

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build the first api docker image
      run: docker build -t api ./api
      shell: bash

    - name: Run the first api docker image
      run: docker run -d -p 8080:8080 api
      shell: bash
    